# infra/argocd/values.yaml
applications:
  # Type 1: A Helm chart from the Git repo
  - name: nginx
    namespace: nginx-prod
    path: argocd/clusters/prod/apps/nginx
    type: helm-git

  - name: it-tools
    namespace: it-tools
    path: argocd/clusters/prod/apps/it-tools
    type: helm-git
  
  - name: vllm
    namespace: vllm-ai
    path: argocd/clusters/prod/apps/vllm
    type: helm-git

  - name: homepage
    namespace: homepage
    path: argocd/clusters/prod/apps/homepage
    type: helm-git

  - name: linkding
    namespace: linkding
    path: argocd/clusters/prod/apps/linkding
    type: helm-git

  - name: bill-splitter
    namespace: bill-splitter
    path: argocd/clusters/prod/apps/bill-splitter
    type: helm-git

  # Type 2: A Helm chart from an external repo
  - name: cert-manager
    namespace: cert-manager
    repo: https://charts.jetstack.io
    chart: cert-manager
    version: v1.18.2
    type: helm-repo
    values:
      installCRDs: true

  - name: nfs-provisioner
    namespace: nfs-provisioner
    type: helm-repo
    repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    chart: nfs-subdir-external-provisioner
    version: 4.0.18
    values:
      replicaCount: 3
      nfs:
        server: 192.168.50.10 #NFS server IP
        path: /volume/91b0517b-7252-4405-85a9-ffdb955809e1/.srv/.unifi-drive/kubestore/.data #NFS share path
      storageClass:
        name: nfs-client
        defaultClass: true    

  # Type 3: Plain YAML files from Git repo
  - name: cluster-issuers
    namespace: cert-manager
    path: argocd/clusters/prod/cluster-config/issuers
    type: plain-git

  - name: nvidia-device-plugin
    namespace: kube-system
    path: argocd/clusters/prod/infra/nvidia-device-plugin
    type: plain-git